##
## =====================================================================================
##  C O P Y R I G H T
## -------------------------------------------------------------------------------------
##  Copyright (c) 2023 by Robert Bosch GmbH. All rights reserved.
##
##  Author(s):
##  - Markus Braun, :em engineering methods AG (contracted by Robert Bosch GmbH)
## =====================================================================================
##

name: "Ensure Everything is initialized for build/test etc."
description: "Installs python and poetry if necessary"
inputs:
  python-version:
    description: "The version of python to use (default: 3.9)"
    required: true
    default: 3.9
  doxygen-version:
    description: "The version of Doxygen to use. 'apt' for distro package or version number like 1.9.8"
    required: true
    default: apt
  doc-tools:
    description: "Whether to install the documentation tools (doxygen)"
    required: true
    default: true
runs:
  using: "composite"
  steps:
    - name: "Ensure doxygen"
      if: ${{ inputs.doc-tools == 'true' }}
      run: |
        set -euo pipefail
        sudo apt-get update

        # install deps
        sudo apt-get install graphviz curl tar -y

        # install doxygen
        bash "${GITHUB_WORKSPACE}/tests/toc/fixtures/install_doxygen.sh" "${{ inputs.doxygen-version }}"
        export PATH="$HOME/.local/bin:$PATH"
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"

        # verify
        if [[ "${{ inputs.doxygen-version }}" == "apt" ]]; then
          installed_version="$(doxygen --version)"
        else
          installed_version="$("$HOME/.local/bin/doxygen" --version)"
        fi

        echo "Installed doxygen version: $installed_version"
      shell: bash

    - name: "Ensure poetry"
      run: pipx install poetry
      shell: bash

    - name: "Ensure python (with poetry caching)"
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "poetry"

    - name: "Ensure dart-sass"
      run: |
        sudo apt-get install -y sass
        sass --version

    - name: "Install dependencies"
      run: poetry install --with=ci
      shell: bash
